import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars: SidebarsConfig = {
  assignments: [
    "index",
    {
      type: `category`,
      label: `1. Student Portfolio`,
      link: {
        type: `doc`,
        id: `student-portfolio/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `1.student-portfolio`,
        },
      ],
    },
    {
      type: `doc`,
      label: `2. Hello GitHub - Lab`,
      id: `hello-world/index`,
    },
    {
      type: `category`,
      label: `3. JS Exercises`,
      link: {
        type: `doc`,
        id: `js-exercises/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `3.js-exercises`,
        },
      ],
    },
    {
      type: `category`,
      label: `4. JS and DOM Exercises`,
      link: {
        type: `doc`,
        id: `js-and-dom-exercises/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `4.js-and-dom-exercises`,
        },
      ],
    },
    {
      type: `category`,
      label: `5. Rock Paper Scissors`,
      link: {
        type: `doc`,
        id: `rock-paper-scissors/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `5.rock-paper-scissors`,
        },
      ],
    },
    {
      type: `category`,
      label: `6. Chatting App`,
      link: {
        type: `doc`,
        id: `chatting-app/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `6.chatting-app`,
        },
      ],
    },
    {
      type: `category`,
      label: `7. Wordle`,
      link: {
        type: `doc`,
        id: `wordle/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `7.wordle`,
        },
      ],
    },
    {
      type: `category`,
      label: `8. React RPS`,
      link: {
        type: `doc`,
        id: `rps-in-react/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `8.rps-in-react`,
        },
      ],
    },
    {
      type: `category`,
      label: `9. Game Hub - routing`,
      link: {
        type: `doc`,
        id: `game-hub/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `9.game-hub`,
        },
      ],
    },
    {
      type: `category`,
      label: `🏁 Game Hub - Final Project `,
      link: {
        type: `doc`,
        id: `final-project/index`,
      },
      items: [
        {
          type: `autogenerated`,
          dirName: `10.final-project`,
        },
      ],
    },
  ]
};

export default sidebars;
